version: 2
registries:
    maven-releases:
        type: maven-repository
        url: https://nexus.vplan.plus/repository/maven-releases/
        username: ${{ secrets.MAVEN_USERNAME }}
        password: ${{ secrets.MAVEN_PASSWORD }}
updates:
    -   package-ecosystem: "gradle"
        directory: "/"
        schedule:
            interval: "daily"
        registries:
            - maven-releases
    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "daily"
