stages:
    - build
    - release

variables:
    PROJECT_MAVEN_USERNAME: "gitlab-ci-token"
    PROJECT_MAVEN_PASSWORD: "$CI_JOB_TOKEN"
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

build:merge-request:
    stage: build
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - .gradle/caches/
            - .gradle/wrapper/
        policy: pull-push
    image:
        name: registry.gitlab.jvbabi.es/vplanplus/infra/docker-android-sdk/android-sdk-jdk:latest
        entrypoint: [""]
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    before_script:
        - echo $SP24_10063764 >> 10063764.txt
        - echo $SP24_20299165 >> 20299165.txt
    script:
        - ./gradlew build --scan --no-daemon
    artifacts:
        paths:
            - build/libs/*.jar
        expire_in: 1 day
        name: "build-artifacts-$CI_COMMIT_SHORT_SHA"

release:build-and-publish:
    stage: release
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - .gradle/caches/
            - .gradle/wrapper/
        policy: pull-push
    rules:
        - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
    image:
        name: registry.gitlab.jvbabi.es/vplanplus/infra/docker-android-sdk/android-sdk-jdk:latest
        entrypoint: [""]
    before_script:
        - echo $SP24_10063764 >> 10063764.txt
        - echo $SP24_20299165 >> 20299165.txt
    script:
        - apt update && apt install -y git
        - |
            YEAR=$(date +'%Y')
            MONTH=$(date +'%m')
            TAG_PREFIX="v${YEAR}.${MONTH}."
            
            LAST_INDEX=$(git tag -l "${TAG_PREFIX}*" | \
              sed -E "s/${TAG_PREFIX}([0-9]+)/\1/" | sort -n | tail -1)
            if [ -z "$LAST_INDEX" ]; then
              NEW_INDEX=1
            else
              NEW_INDEX=$((LAST_INDEX + 1))
            fi
            NEW_TAG="${TAG_PREFIX}${NEW_INDEX}"
            echo "Version: $NEW_TAG"
            echo "version=$NEW_TAG" >> local.properties
            echo "NEW_TAG=$NEW_TAG" >> build.env

        - ./gradlew clean publishAllPublicationsToReleasesRepository --no-daemon

    artifacts:
        reports:
            dotenv: build.env

create:gitlab-release:
    stage: release
    needs:
        - release:build-and-publish
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    script:
        - echo "Releasing ${NEW_TAG}"
    release:
        tag_name: $NEW_TAG
        ref: $CI_COMMIT_SHA
        description: "Automated release $NEW_TAG"